### ISSUE TITLE
Does it work with Supertest?

### ISSUE THREAD

**Issue by rosendi** [aneilbaboo/replayer#13]
Jest fails with:

```
TypeError: Cannot read property 'status' of undefined

      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:263:10)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:171:18)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at node_modules/supertest/lib/test.js:128:5
      at Test.Object.<anonymous>.Request.callback (node_modules/superagent/lib/node/index.js:688:3)
      at EventEmitter.<anonymous> (node_modules/superagent/lib/node/index.js:615:10)
      at Object.onceWrapper (events.js:293:19)
      at emitOne (events.js:96:13)
      at EventEmitter.emit (events.js:191:7)
      at playback (node_modules/replayer/src/cache.js:179:15)
      at EventEmitter.<anonymous> (node_modules/replayer/src/cache.js:345:11)
      at emitOne (events.js:101:20)
      at EventEmitter.emit (events.js:191:7)
      at playback (node_modules/replayer/src/cache.js:179:15)
      at EventEmitter.req.end (node_modules/replayer/src/cache.js:216:9)
      at EventEmitter.req.end (node_modules/replayer/src/cache.js:362:15)
      at Test.Object.<anonymous>.Request._end (node_modules/superagent/lib/node/index.js:961:9)
      at Test.Object.<anonymous>.Request.end (node_modules/superagent/lib/node/index.js:761:15)
      at Test.Object.<anonymous>.Test.end (node_modules/supertest/lib/test.js:125:7)
      at node_modules/superagent/lib/request-base.js:194:12
      at Test.then (node_modules/superagent/lib/request-base.js:193:31)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by aneilbaboo** [comment]
Hi Dimitri - Sorry for the delay.  Can you provide a snippet that produces the error?

**Comment by rosendi** [comment]
@aneilbaboo Well... I switched to Nock, so don't have an example.
